apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-route53-clusterissuer
spec:
  acme:
    email: ferdy.muller@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    #https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-clusterissuer-route53-secret    
    solvers:
    - selector:
        dnsZones:
        - 'vbarba.site'    
      dns01:  
        route53:
          region: us-east-1
          accessKeyID: AKIA32EVOJ34BAXU65MR 
          secretAccessKeySecretRef:
            name: route53-secret
            key: secret-access-key
